# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='wildChicken', max_length=255)),
                ('meta', models.TextField(null=True)),
            ],
        ),
    ]
