# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0005_tcuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGoodReview', models.BooleanField(default=False)),
                ('isNeutralRevivew', models.BooleanField(default=False)),
                ('isBadReview', models.BooleanField(default=False)),
                ('body', models.TextField(null=True)),
                ('dateTime', models.DateTimeField()),
                ('likeCount', models.IntegerField(default=0)),
                ('dislikeCount', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseOperation.TCUser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseOperation.Course')),
            ],
        ),
    ]
