# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0006_coursereview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherPoiner',
            new_name='TeacherPointer',
        ),
    ]
