# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0009_auto_20160907_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacherSet',
            field=models.ManyToManyField(to='databaseOperation.TeacherPointer'),
        ),
    ]
