# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0010_auto_20160907_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherpointer',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseOperation.Teacher'),
        ),
    ]
