# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0011_auto_20160907_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='isScoredReview',
            field=models.BooleanField(default=False),
        ),
    ]
