# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0012_coursereview_isscoredreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='followCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='scoreCount',
            field=models.IntegerField(default=0),
        ),
    ]
