# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0013_auto_20160907_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseOperation.TCUser'),
        ),
    ]
