# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0015_auto_20160907_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
    ]
