# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0016_course_islocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseOperation.School'),
        ),
    ]
