# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 02:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0017_tcuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 9, 2, 22, 32, 943172, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
