# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0020_auto_20160909_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='dislikeBy',
            field=models.ManyToManyField(related_name='dislikeBy', to='databaseOperation.TCUser'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='likeBy',
            field=models.ManyToManyField(related_name='likeBy', to='databaseOperation.TCUser'),
        ),
    ]
