# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0021_auto_20160911_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='dislikeBy',
            field=models.ManyToManyField(blank=True, related_name='dislikeBy', to='databaseOperation.TCUser'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='likeBy',
            field=models.ManyToManyField(blank=True, related_name='likeBy', to='databaseOperation.TCUser'),
        ),
    ]
