# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0022_auto_20160911_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='collectBy',
            field=models.ManyToManyField(blank=True, related_name='collectBy', to='databaseOperation.TCUser'),
        ),
    ]
