# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0023_coursereview_collectby'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='collectCount',
            field=models.IntegerField(default=0),
        ),
    ]
