# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseOperation', '0024_coursereview_collectcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcuser',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
